version: "3.7"

services:
  db:
    image: mariadb:10.2
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress

  wordpress:
    image: ziodave/wordpress-xdebug:5.8.3-php8.0
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - wordpress-data:/var/www/html
      - .:/var/www/html/wp-content/plugins/wp-all-import-wordlift-add-on
      - .docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    env_file:
      - ./.env
    environment:
      PHP_IDE_CONFIG: serverName=wordpress-nginx
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: "1"
      WORDPRESS_CONFIG_EXTRA: |        
        if ( isset( $$_SERVER['HTTP_X_FORWARDED_HOST'] ) ) {
          $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
        }

        # Define the site and home URLs.
        define( 'WP_SITEURL', 'https://wordlift-addon.www.localhost' );
        define( 'WP_HOME', WP_SITEURL );
        
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.21.5
    ports:
      - "443:443"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html/wp-content/plugins/wp-all-import-wordlift-add-on
    environment:
      NGINX_HOST_NAME: "${COMPOSE_PROJECT_NAME}"
    command: /bin/bash -c "envsubst '$$NGINX_HOST_NAME' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/wordpress.conf && nginx -g 'daemon off;'"

  cli:
    image: wordpress:cli-2.5-php8.0
    depends_on:
      - db
    user: xfs
    volumes:
      - .:/var/www/html

volumes:
  db-data:
  wordpress-data: